# Generated by Django 3.0.5 on 2020-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
    ]
